name: Create Issues from Project Plan

on:
  workflow_dispatch:   # Permite activarlo manualmente desde la UI de GitHub
  push:
    branches:
      - main

jobs:
  create_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run create issues script
        env:
          TOKEN_PAT: ${{ secrets.TOKEN_PAT }}
        run: |
          python .github/scripts/create_issues.py
